export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const FETCH_PROPERTIES_REQUEST = "FETCH_PROPERTIES_REQUEST";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";
export const FETCH_PROPERTIES_FAILURE = "FETCH_PROPERTIES_FAILURE";
export const FETCH_PROPERTY_REQUEST = "FETCH_PROPERTY_REQUEST";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY_SUCCESS";
export const FETCH_PROPERTY_FAILURE = "FETCH_PROPERTY_FAILURE";
export const FETCH_IMAGES_REQUEST = "FETCH_IMAGES_REQUEST";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";
export const MAKE_OFFER_REQUEST = "MAKE_OFFER_REQUEST";
export const MAKE_OFFER_SUCCESS = "MAKE_OFFER_SUCCESS";
export const MAKE_OFFER_FAILURE = "MAKE_OFFER_FAILURE";
export const SET_PROPERTY_FILTER = "SET_PROPERTY_FILTER";
export const FETCH_FILTERED_PROPERTIES_REQUEST =
  "FETCH_FILTERED_PROPERTIES_REQUEST";
export const FETCH_FILTERED_PROPERTIES_SUCCESS =
  "FETCH_FILTERED_PROPERTIES_SUCCESS";
export const FETCH_FILTERED_PROPERTIES_FAILURE =
  "FETCH_FILTERED_PROPERTIES_FAILURE";
export const POST_ADDRESS_REQUEST = "POST_ADDRESS_REQUEST";
export const POST_ADDRESS_SUCCESS = "POST_ADDRESS_SUCCESS";
export const POST_ADDRESS_FAILURE = "POST_ADDRESS_FAILURE";
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";
export const FETCH_MY_PROFILE_REQUEST = "FETCH_MY_PROFILE_REQUEST";
export const FETCH_MY_PROFILE_SUCCESS = "FETCH_MY_PROFILE_SUCCESS";
export const FETCH_MY_PROFILE_FAILURE = "FETCH_MY_PROFILE_FAILURE";
export const FETCH_OFFERS_BY_USER_REQUEST = "FETCH_OFFERS_BY_USER_REQUEST";
export const FETCH_OFFERS_BY_USER_SUCCESS = "FETCH_OFFERS_BY_USER_SUCCESS";
export const FETCH_OFFERS_BY_USER_FAILURE = "FETCH_OFFERS_BY_USER_FAILURE";
export const FETCH_REQUESTS_BY_ADDRESS_REQUEST =
  "FETCH_REQUESTS_BY_ADDRESS_REQUEST";
export const FETCH_REQUESTS_BY_ADDRESS_SUCCESS =
  "FETCH_REQUESTS_BY_ADDRESS_SUCCESS";
export const FETCH_REQUESTS_BY_ADDRESS_FAILURE =
  "FETCH_REQUESTS_BY_ADDRESS_FAILURE";
export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";
export const ADD_PROPERTY_REQUEST = "ADD_PROPERTY_REQUEST";
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const ADD_PROPERTY_FAILURE = "ADD_PROPERTY_FAILURE";
export const ADD_NEW_BUYER_FAILURE = "ADD_NEW_BUYER_FAILURE";
export const ADD_NEW_BUYER_REQUEST = "ADD_NEW_BUYER_REQUEST";
export const ADD_NEW_BUYER_SUCCESS = "ADD_NEW_BUYER_SUCCESS";
export const Update_BUYER_FAILURE = "Update_BUYER_FAILURE";
export const Update_BUYER_REQUEST = "Update_BUYER_REQUEST";
export const Update_BUYER_SUCCESS = "Update_BUYER_SUCCESS";
export const FETCH_Buyer_REQUEST = "FETCH_Buyer_REQUEST";
export const FETCH_BUYER_SUCCESS = "FETCH_BUYER_SUCCESS";
export const FETCH_BUYER_FAILURE = "FETCH_BUYER_FAILURE";
export const FETCH_OFFERS_BY_SELLER_REQUEST = "FETCH_OFFERS_BY_SELLER_REQUEST";
export const FETCH_OFFERS_BY_SELLER_SUCCESS = "FETCH_OFFERS_BY_SELLER_SUCCESS";
export const ADD_NEW_USER_FAILURE = "ADD_NEW_USER_FAILURE";
export const ADD_NEW_USER_REQUEST = "ADD_NEW_USER_REQUEST";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";

export const Update_USER_REQUEST = "Update_USER_REQUEST";
export const Update_USER_SUCCESS = "Update_USER_SUCCESS";
export const Update_USER_FAILURE = "Update_USER_FAILURE";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAILURE = "UPDATE_PROPERTY_FAILURE";

export const ACCEPT_OFFER_REQUEST = "ACCEPT_OFFER_REQUEST";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
export const ACCEPT_OFFER_FAILURE = "ACCEPT_OFFER_FAILURE";

export const REFUSE_OFFER_REQUEST = "REFUSE_OFFER_REQUEST";
export const REFUSE_OFFER_SUCCESS = "REFUSE_OFFER_SUCCESS";
export const REFUSE_OFFER_FAILURE = "REFUSE_OFFER_FAILURE";

export const FETCH_OFFERS_BY_SELLER_FAILURE = "FETCH_OFFERS_BY_SELLER_FAILURE";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";

export const DELETE_BUYER_REQUEST = "DELETE_BUYER_REQUEST";
export const DELETE_BUYER_SUCCESS = "DELETE_BUYER_SUCCESS";
export const DELETE_BUYER_FAILURE = "DELETE_BUYER_FAILURE";

export const FETCH_BUYER_BY_ID_REQUEST = "FETCH_BUYER_BY_ID_REQUEST";
export const FETCH_BUYER_BY_ID_SUCCESS = "FETCH_BUYER_BY_ID_REQUEST";
export const FETCH_BUYER_BY_ID_FAILURE = "FETCH_BUYER_BY_ID_REQUEST";

export const FETCH_OFFERS_BY_PROPERTY_ID_REQUEST =
  "FETCH_OFFERS_BY_PROPERTY_ID_REQUEST";
export const FETCH_OFFERS_BY_PROPERTY_ID_SUCCESS =
  "FETCH_OFFERS_BY_PROPERTY_ID_SUCCESS";
export const FETCH_OFFERS_BY_PROPERTY_ID_FAILURE =
  "FETCH_OFFERS_BY_PROPERTY_ID_FAILURE";

export const CREATE_CAMPAIGN_REQUEST = "CREATE_CAMPAIGN_REQUEST";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILURE = "CREATE_CAMPAIGN_FAILURE";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAILURE = "DELETE_OFFER_FAILURE";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

export const FETCH_ADDRESS_REQUEST_BY_ID_REQUEST =
  "FETCH_ADDRESS_REQUEST_BY_ID_REQUEST";
export const FETCH_ADDRESS_REQUEST_BY_ID_SUCCESS =
  "FETCH_ADDRESS_REQUEST_BY_ID_SUCCESS";
export const FETCH_ADDRESS_REQUEST_BY_ID_FAILURE =
  "FETCH_ADDRESS_REQUEST_BY_ID_FAILURE";

export const ACCEPT_REQUEST_REQUEST = "ACCEPT_REQUEST_REQUEST";
export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAILURE = "ACCEPT_REQUEST_FAILURE";

export const REFUSE_REQUEST_REQUEST = "REFUSE_REQUEST_REQUEST";
export const REFUSE_REQUEST_SUCCESS = "REFUSE_REQUEST_SUCCESS";
export const REFUSE_REQUEST_FAILURE = "REFUSE_REQUEST_FAILURE";

export const FETCH_ALL_CAMPAIGNS_REQUEST = "FETCH_ALL_CAMPAIGNS_REQUEST";
export const FETCH_ALL_CAMPAIGNS_SUCCESS = "FETCH_ALL_CAMPAIGNS_SUCCESS";
export const FETCH_ALL_CAMPAIGNS_FAILURE = "FETCH_ALL_CAMPAIGNS_FAILURE";

export const SEND_REPLY_REQUEST = "SEND_REPLY_REQUEST";
export const SEND_REPLY_SUCCESS = "SEND_REPLY_SUCCESS";
export const SEND_REPLY_FAILURE = "SEND_REPLY_FAILURE";
